version: '3'
services:
  backend:
    build: ./back-end
    ports:
      - "5000:5000"
    volumes:
      - ./back-end:/app
    depends_on:
      - db
    environment:
      - FLASK_APP=app.py
    command: flask run --host=0.0.0.0

  frontend:
    build: ./front-end
    ports:
      - "3000:80"
    volumes:
      - ./front-end:/usr/share/nginx/html
    command: ["nginx", "-g", "daemon off;"]

  db:
    build: ./data-base
    volumes:
      - ./data-base:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"